import type { IPhoneModel } from "@/lib/schemas";

const baseCameras = {
  dual14: [
    {
      id: "ultra-wide",
      name: "Ultra Wide",
      type: "ultra-wide" as const,
      focalLengthMm: 13,
      aperture: "f/2.4",
      megapixels: 12,
    },
    {
      id: "wide",
      name: "Main",
      type: "wide" as const,
      focalLengthMm: 26,
      aperture: "f/1.5",
      megapixels: 12,
    },
    {
      id: "front",
      name: "TrueDepth",
      type: "front" as const,
      megapixels: 12,
    },
  ],
  triplePro14: [
    {
      id: "ultra-wide",
      name: "Ultra Wide",
      type: "ultra-wide" as const,
      focalLengthMm: 13,
      aperture: "f/2.2",
      megapixels: 12,
    },
    {
      id: "wide",
      name: "Main",
      type: "wide" as const,
      focalLengthMm: 24,
      aperture: "f/1.78",
      megapixels: 48,
    },
    {
      id: "telephoto",
      name: "Telephoto",
      type: "telephoto" as const,
      focalLengthMm: 77,
      aperture: "f/2.8",
      megapixels: 12,
    },
    {
      id: "front",
      name: "TrueDepth",
      type: "front" as const,
      megapixels: 12,
    },
  ],
};

function model(
  partial: Omit<IPhoneModel, "status" | "lastVerifiedAt" | "author" | "reviewer"> &
    Partial<Pick<IPhoneModel, "status" | "lastVerifiedAt" | "author" | "reviewer">>,
): IPhoneModel {
  return {
    status: "published",
    lastVerifiedAt: "2026-07-01",
    author: "Editorial",
    reviewer: "Editorial",
    ...partial,
  };
}

export const models: IPhoneModel[] = [
  model({
    id: "iphone-16-pro",
    name: "iPhone 16 Pro",
    slug: "iphone-16-pro",
    family: "iphone-16-pro",
    releaseYear: 2024,
    supportedIOS: ["18", "19"],
    cameras: [
      {
        id: "ultra-wide",
        name: "Ultra Wide",
        type: "ultra-wide",
        focalLengthMm: 13,
        aperture: "f/2.2",
        megapixels: 48,
      },
      {
        id: "wide",
        name: "Fusion Main",
        type: "wide",
        focalLengthMm: 24,
        aperture: "f/1.78",
        megapixels: 48,
      },
      {
        id: "telephoto",
        name: "5x Telephoto",
        type: "telephoto",
        focalLengthMm: 120,
        aperture: "f/2.8",
        megapixels: 12,
      },
      {
        id: "front",
        name: "TrueDepth",
        type: "front",
        megapixels: 12,
      },
    ],
    features: {
      proRAW: true,
      proRes: true,
      cinematicMode: true,
      actionMode: true,
      photographicStyles: true,
      nightMode: true,
      macro: true,
      appleLog: true,
      spatialVideo: true,
      maxPhotoResolution: "48MP",
      videoResolutions: ["4K60", "4K120", "1080p240"],
      lenses: ["0.5x", "1x", "2x", "5x"],
    },
    sourceIds: ["apple-iphone-16-pro-specs", "apple-camera-user-guide", "test-16pro-night-2026"],
  }),
  model({
    id: "iphone-16-pro-max",
    name: "iPhone 16 Pro Max",
    slug: "iphone-16-pro-max",
    family: "iphone-16-pro",
    releaseYear: 2024,
    supportedIOS: ["18", "19"],
    cameras: [
      {
        id: "ultra-wide",
        name: "Ultra Wide",
        type: "ultra-wide",
        focalLengthMm: 13,
        aperture: "f/2.2",
        megapixels: 48,
      },
      {
        id: "wide",
        name: "Fusion Main",
        type: "wide",
        focalLengthMm: 24,
        aperture: "f/1.78",
        megapixels: 48,
      },
      {
        id: "telephoto",
        name: "5x Telephoto",
        type: "telephoto",
        focalLengthMm: 120,
        aperture: "f/2.8",
        megapixels: 12,
      },
      {
        id: "front",
        name: "TrueDepth",
        type: "front",
        megapixels: 12,
      },
    ],
    features: {
      proRAW: true,
      proRes: true,
      cinematicMode: true,
      actionMode: true,
      photographicStyles: true,
      nightMode: true,
      macro: true,
      appleLog: true,
      spatialVideo: true,
      maxPhotoResolution: "48MP",
      videoResolutions: ["4K60", "4K120", "1080p240"],
      lenses: ["0.5x", "1x", "2x", "5x"],
    },
    sourceIds: ["apple-iphone-16-pro-specs", "apple-camera-user-guide"],
  }),
  model({
    id: "iphone-16",
    name: "iPhone 16",
    slug: "iphone-16",
    family: "iphone-16",
    releaseYear: 2024,
    supportedIOS: ["18", "19"],
    cameras: [
      {
        id: "ultra-wide",
        name: "Ultra Wide",
        type: "ultra-wide",
        focalLengthMm: 13,
        aperture: "f/2.2",
        megapixels: 12,
      },
      {
        id: "wide",
        name: "Fusion Main",
        type: "wide",
        focalLengthMm: 26,
        aperture: "f/1.6",
        megapixels: 48,
      },
      {
        id: "front",
        name: "TrueDepth",
        type: "front",
        megapixels: 12,
      },
    ],
    features: {
      proRAW: false,
      proRes: false,
      cinematicMode: true,
      actionMode: true,
      photographicStyles: true,
      nightMode: true,
      macro: false,
      maxPhotoResolution: "48MP",
      videoResolutions: ["4K60", "1080p240"],
      lenses: ["0.5x", "1x", "2x"],
    },
    sourceIds: ["apple-iphone-16-specs", "apple-camera-user-guide"],
  }),
  model({
    id: "iphone-16-plus",
    name: "iPhone 16 Plus",
    slug: "iphone-16-plus",
    family: "iphone-16",
    releaseYear: 2024,
    supportedIOS: ["18", "19"],
    cameras: [
      {
        id: "ultra-wide",
        name: "Ultra Wide",
        type: "ultra-wide",
        focalLengthMm: 13,
        aperture: "f/2.2",
        megapixels: 12,
      },
      {
        id: "wide",
        name: "Fusion Main",
        type: "wide",
        focalLengthMm: 26,
        aperture: "f/1.6",
        megapixels: 48,
      },
      {
        id: "front",
        name: "TrueDepth",
        type: "front",
        megapixels: 12,
      },
    ],
    features: {
      proRAW: false,
      proRes: false,
      cinematicMode: true,
      actionMode: true,
      photographicStyles: true,
      nightMode: true,
      macro: false,
      maxPhotoResolution: "48MP",
      videoResolutions: ["4K60", "1080p240"],
      lenses: ["0.5x", "1x", "2x"],
    },
    sourceIds: ["apple-iphone-16-specs", "apple-camera-user-guide"],
  }),
  model({
    id: "iphone-15-pro",
    name: "iPhone 15 Pro",
    slug: "iphone-15-pro",
    family: "iphone-15-pro",
    releaseYear: 2023,
    supportedIOS: ["17", "18", "19"],
    cameras: [
      {
        id: "ultra-wide",
        name: "Ultra Wide",
        type: "ultra-wide",
        focalLengthMm: 13,
        aperture: "f/2.2",
        megapixels: 12,
      },
      {
        id: "wide",
        name: "Main",
        type: "wide",
        focalLengthMm: 24,
        aperture: "f/1.78",
        megapixels: 48,
      },
      {
        id: "telephoto",
        name: "3x Telephoto",
        type: "telephoto",
        focalLengthMm: 77,
        aperture: "f/2.8",
        megapixels: 12,
      },
      {
        id: "front",
        name: "TrueDepth",
        type: "front",
        megapixels: 12,
      },
    ],
    features: {
      proRAW: true,
      proRes: true,
      cinematicMode: true,
      actionMode: true,
      photographicStyles: true,
      nightMode: true,
      macro: true,
      maxPhotoResolution: "48MP",
      videoResolutions: ["4K60", "1080p240"],
      lenses: ["0.5x", "1x", "2x", "3x"],
    },
    sourceIds: ["apple-iphone-15-pro-specs", "apple-camera-user-guide", "test-15pro-portrait-2026"],
  }),
  model({
    id: "iphone-15-pro-max",
    name: "iPhone 15 Pro Max",
    slug: "iphone-15-pro-max",
    family: "iphone-15-pro",
    releaseYear: 2023,
    supportedIOS: ["17", "18", "19"],
    cameras: [
      {
        id: "ultra-wide",
        name: "Ultra Wide",
        type: "ultra-wide",
        focalLengthMm: 13,
        aperture: "f/2.2",
        megapixels: 12,
      },
      {
        id: "wide",
        name: "Main",
        type: "wide",
        focalLengthMm: 24,
        aperture: "f/1.78",
        megapixels: 48,
      },
      {
        id: "telephoto",
        name: "5x Telephoto",
        type: "telephoto",
        focalLengthMm: 120,
        aperture: "f/2.8",
        megapixels: 12,
      },
      {
        id: "front",
        name: "TrueDepth",
        type: "front",
        megapixels: 12,
      },
    ],
    features: {
      proRAW: true,
      proRes: true,
      cinematicMode: true,
      actionMode: true,
      photographicStyles: true,
      nightMode: true,
      macro: true,
      maxPhotoResolution: "48MP",
      videoResolutions: ["4K60", "1080p240"],
      lenses: ["0.5x", "1x", "2x", "5x"],
    },
    sourceIds: ["apple-iphone-15-pro-specs", "apple-camera-user-guide"],
  }),
  model({
    id: "iphone-15",
    name: "iPhone 15",
    slug: "iphone-15",
    family: "iphone-15",
    releaseYear: 2023,
    supportedIOS: ["17", "18", "19"],
    cameras: [
      {
        id: "ultra-wide",
        name: "Ultra Wide",
        type: "ultra-wide",
        focalLengthMm: 13,
        aperture: "f/2.4",
        megapixels: 12,
      },
      {
        id: "wide",
        name: "Main",
        type: "wide",
        focalLengthMm: 26,
        aperture: "f/1.6",
        megapixels: 48,
      },
      {
        id: "front",
        name: "TrueDepth",
        type: "front",
        megapixels: 12,
      },
    ],
    features: {
      proRAW: false,
      proRes: false,
      cinematicMode: true,
      actionMode: true,
      photographicStyles: true,
      nightMode: true,
      macro: false,
      maxPhotoResolution: "48MP",
      videoResolutions: ["4K60", "1080p60"],
      lenses: ["0.5x", "1x", "2x"],
    },
    sourceIds: ["apple-iphone-15-specs", "apple-camera-user-guide"],
  }),
  model({
    id: "iphone-15-plus",
    name: "iPhone 15 Plus",
    slug: "iphone-15-plus",
    family: "iphone-15",
    releaseYear: 2023,
    supportedIOS: ["17", "18", "19"],
    cameras: [
      {
        id: "ultra-wide",
        name: "Ultra Wide",
        type: "ultra-wide",
        focalLengthMm: 13,
        aperture: "f/2.4",
        megapixels: 12,
      },
      {
        id: "wide",
        name: "Main",
        type: "wide",
        focalLengthMm: 26,
        aperture: "f/1.6",
        megapixels: 48,
      },
      {
        id: "front",
        name: "TrueDepth",
        type: "front",
        megapixels: 12,
      },
    ],
    features: {
      proRAW: false,
      proRes: false,
      cinematicMode: true,
      actionMode: true,
      photographicStyles: true,
      nightMode: true,
      macro: false,
      maxPhotoResolution: "48MP",
      videoResolutions: ["4K60", "1080p60"],
      lenses: ["0.5x", "1x", "2x"],
    },
    sourceIds: ["apple-iphone-15-specs", "apple-camera-user-guide"],
  }),
  model({
    id: "iphone-14-pro",
    name: "iPhone 14 Pro",
    slug: "iphone-14-pro",
    family: "iphone-14-pro",
    releaseYear: 2022,
    supportedIOS: ["16", "17", "18", "19"],
    cameras: baseCameras.triplePro14,
    features: {
      proRAW: true,
      proRes: true,
      cinematicMode: true,
      actionMode: true,
      photographicStyles: true,
      nightMode: true,
      macro: true,
      maxPhotoResolution: "48MP",
      videoResolutions: ["4K60", "1080p240"],
      lenses: ["0.5x", "1x", "2x", "3x"],
    },
    sourceIds: ["apple-iphone-14-pro-specs", "apple-camera-user-guide"],
  }),
  model({
    id: "iphone-14-pro-max",
    name: "iPhone 14 Pro Max",
    slug: "iphone-14-pro-max",
    family: "iphone-14-pro",
    releaseYear: 2022,
    supportedIOS: ["16", "17", "18", "19"],
    cameras: baseCameras.triplePro14,
    features: {
      proRAW: true,
      proRes: true,
      cinematicMode: true,
      actionMode: true,
      photographicStyles: true,
      nightMode: true,
      macro: true,
      maxPhotoResolution: "48MP",
      videoResolutions: ["4K60", "1080p240"],
      lenses: ["0.5x", "1x", "2x", "3x"],
    },
    sourceIds: ["apple-iphone-14-pro-specs", "apple-camera-user-guide"],
  }),
  model({
    id: "iphone-14",
    name: "iPhone 14",
    slug: "iphone-14",
    family: "iphone-14",
    releaseYear: 2022,
    supportedIOS: ["16", "17", "18", "19"],
    cameras: baseCameras.dual14,
    features: {
      proRAW: false,
      proRes: false,
      cinematicMode: true,
      actionMode: true,
      photographicStyles: true,
      nightMode: true,
      macro: false,
      maxPhotoResolution: "12MP",
      videoResolutions: ["4K60", "1080p60"],
      lenses: ["0.5x", "1x", "2x"],
    },
    sourceIds: ["apple-iphone-14-specs", "apple-camera-user-guide"],
  }),
  model({
    id: "iphone-14-plus",
    name: "iPhone 14 Plus",
    slug: "iphone-14-plus",
    family: "iphone-14",
    releaseYear: 2022,
    supportedIOS: ["16", "17", "18", "19"],
    cameras: baseCameras.dual14,
    features: {
      proRAW: false,
      proRes: false,
      cinematicMode: true,
      actionMode: true,
      photographicStyles: true,
      nightMode: true,
      macro: false,
      maxPhotoResolution: "12MP",
      videoResolutions: ["4K60", "1080p60"],
      lenses: ["0.5x", "1x", "2x"],
    },
    sourceIds: ["apple-iphone-14-specs", "apple-camera-user-guide"],
  }),
  model({
    id: "iphone-13-pro",
    name: "iPhone 13 Pro",
    slug: "iphone-13-pro",
    family: "iphone-13-pro",
    releaseYear: 2021,
    supportedIOS: ["15", "16", "17", "18", "19"],
    cameras: [
      {
        id: "ultra-wide",
        name: "Ultra Wide",
        type: "ultra-wide",
        focalLengthMm: 13,
        aperture: "f/1.8",
        megapixels: 12,
      },
      {
        id: "wide",
        name: "Main",
        type: "wide",
        focalLengthMm: 26,
        aperture: "f/1.5",
        megapixels: 12,
      },
      {
        id: "telephoto",
        name: "3x Telephoto",
        type: "telephoto",
        focalLengthMm: 77,
        aperture: "f/2.8",
        megapixels: 12,
      },
      {
        id: "front",
        name: "TrueDepth",
        type: "front",
        megapixels: 12,
      },
    ],
    features: {
      proRAW: true,
      proRes: true,
      cinematicMode: true,
      actionMode: false,
      photographicStyles: true,
      nightMode: true,
      macro: true,
      maxPhotoResolution: "12MP",
      videoResolutions: ["4K60", "1080p240"],
      lenses: ["0.5x", "1x", "3x"],
    },
    sourceIds: ["apple-iphone-13-pro-specs", "apple-camera-user-guide"],
  }),
  model({
    id: "iphone-13-pro-max",
    name: "iPhone 13 Pro Max",
    slug: "iphone-13-pro-max",
    family: "iphone-13-pro",
    releaseYear: 2021,
    supportedIOS: ["15", "16", "17", "18", "19"],
    cameras: [
      {
        id: "ultra-wide",
        name: "Ultra Wide",
        type: "ultra-wide",
        focalLengthMm: 13,
        aperture: "f/1.8",
        megapixels: 12,
      },
      {
        id: "wide",
        name: "Main",
        type: "wide",
        focalLengthMm: 26,
        aperture: "f/1.5",
        megapixels: 12,
      },
      {
        id: "telephoto",
        name: "3x Telephoto",
        type: "telephoto",
        focalLengthMm: 77,
        aperture: "f/2.8",
        megapixels: 12,
      },
      {
        id: "front",
        name: "TrueDepth",
        type: "front",
        megapixels: 12,
      },
    ],
    features: {
      proRAW: true,
      proRes: true,
      cinematicMode: true,
      actionMode: false,
      photographicStyles: true,
      nightMode: true,
      macro: true,
      maxPhotoResolution: "12MP",
      videoResolutions: ["4K60", "1080p240"],
      lenses: ["0.5x", "1x", "3x"],
    },
    sourceIds: ["apple-iphone-13-pro-specs", "apple-camera-user-guide"],
  }),
  model({
    id: "iphone-13",
    name: "iPhone 13",
    slug: "iphone-13",
    family: "iphone-13",
    releaseYear: 2021,
    supportedIOS: ["15", "16", "17", "18", "19"],
    cameras: [
      {
        id: "ultra-wide",
        name: "Ultra Wide",
        type: "ultra-wide",
        focalLengthMm: 13,
        aperture: "f/2.4",
        megapixels: 12,
      },
      {
        id: "wide",
        name: "Main",
        type: "wide",
        focalLengthMm: 26,
        aperture: "f/1.6",
        megapixels: 12,
      },
      {
        id: "front",
        name: "TrueDepth",
        type: "front",
        megapixels: 12,
      },
    ],
    features: {
      proRAW: false,
      proRes: false,
      cinematicMode: true,
      actionMode: false,
      photographicStyles: true,
      nightMode: true,
      macro: false,
      maxPhotoResolution: "12MP",
      videoResolutions: ["4K60", "1080p60"],
      lenses: ["0.5x", "1x", "2x"],
    },
    sourceIds: ["apple-iphone-13-specs", "apple-camera-user-guide"],
  }),
  model({
    id: "iphone-13-mini",
    name: "iPhone 13 mini",
    slug: "iphone-13-mini",
    family: "iphone-13",
    releaseYear: 2021,
    supportedIOS: ["15", "16", "17", "18", "19"],
    cameras: [
      {
        id: "ultra-wide",
        name: "Ultra Wide",
        type: "ultra-wide",
        focalLengthMm: 13,
        aperture: "f/2.4",
        megapixels: 12,
      },
      {
        id: "wide",
        name: "Main",
        type: "wide",
        focalLengthMm: 26,
        aperture: "f/1.6",
        megapixels: 12,
      },
      {
        id: "front",
        name: "TrueDepth",
        type: "front",
        megapixels: 12,
      },
    ],
    features: {
      proRAW: false,
      proRes: false,
      cinematicMode: true,
      actionMode: false,
      photographicStyles: true,
      nightMode: true,
      macro: false,
      maxPhotoResolution: "12MP",
      videoResolutions: ["4K60", "1080p60"],
      lenses: ["0.5x", "1x", "2x"],
    },
    sourceIds: ["apple-iphone-13-specs", "apple-camera-user-guide"],
  }),
];

export const modelsById = Object.fromEntries(models.map((m) => [m.id, m]));
export const modelsBySlug = Object.fromEntries(models.map((m) => [m.slug, m]));
