import type { Recommendation } from "@/lib/schemas";

function rec(
  partial: Omit<Recommendation, "status" | "lastVerifiedAt" | "author" | "reviewer" | "warnings" | "requiredFeatures"> &
    Partial<
      Pick<
        Recommendation,
        | "status"
        | "lastVerifiedAt"
        | "author"
        | "reviewer"
        | "warnings"
        | "requiredFeatures"
      >
    >,
): Recommendation {
  return {
    status: "published",
    lastVerifiedAt: "2026-07-15",
    author: "Editorial",
    reviewer: "Editorial",
    warnings: [],
    requiredFeatures: [],
    ...partial,
  };
}

export const recommendations: Recommendation[] = [
  rec({
    id: "16pro-everyday-photo-daylight",
    modelIds: ["iphone-16-pro", "iphone-16-pro-max"],
    familyIds: ["iphone-16-pro"],
    mediaType: "photo",
    scenario: "everyday",
    lighting: ["daylight", "overcast"],
    outputGoals: ["private-sharing", "instagram", "save-storage"],
    summary:
      "Use Photo mode at 1x with HEIF High Efficiency and let Smart HDR handle contrast. Keep Photographic Style on Standard or Vibrant for quick sharing.",
    settings: {
      mode: "Photo",
      lens: "1x Main",
      format: "HEIF High Efficiency",
      resolution: "24MP (default) or 12MP for storage",
      hdr: "Smart HDR on (automatic)",
      nightMode: "Off in daylight",
      flash: "Off",
      exposure: "Tap subject; nudge brightness if faces are dark",
      focus: "Tap to focus; lock AE/AF for consistent scenes",
      photographicStyle: "Standard or Vibrant",
    },
    instructions: [
      "Open Camera and confirm Photo mode (not Portrait or Cinematic).",
      "Select 1x. Use 0.5x only when you need more of the scene.",
      "In Settings → Camera → Formats, choose High Efficiency.",
      "Tap the subject, adjust the sun slider if needed, then shoot.",
      "For people, step closer instead of digitally zooming past 2x.",
    ],
    rationale: [
      {
        claim: "The Fusion main camera is the highest-quality stills path on 16 Pro.",
        sourceIds: ["apple-iphone-16-pro-specs"],
      },
      {
        claim: "HEIF is Apple’s default efficient photo format.",
        sourceIds: ["apple-heif-support"],
      },
    ],
    alternatives: [
      {
        label: "Maximum quality",
        reason: "Keep more detail for later edits or prints.",
        settingsSummary: "HEIF or ProRAW · 48MP when light is strong · Standard style",
        tradeoff: "Larger files and slower capture/processing.",
      },
      {
        label: "Save storage",
        reason: "Everyday snaps fill libraries quickly.",
        settingsSummary: "HEIF · 12MP · Live Photos off",
        tradeoff: "Less crop flexibility later.",
      },
    ],
    mistakes: [
      "Pinching to 5x for casual shots—detail drops fast.",
      "Leaving the lens dirty; wipe glass before important photos.",
      "Using flash outdoors in daylight.",
    ],
    accessoryTags: ["MagSafe grip"],
    appTags: ["edit-photo"],
    confidence: "high",
    evidence: [
      "Apple iPhone 16 Pro specs",
      "Apple Camera User Guide",
      "HEIF support documentation",
    ],
    requiredFeatures: [],
  }),
  rec({
    id: "16pro-night-photo",
    modelIds: ["iphone-16-pro", "iphone-16-pro-max"],
    familyIds: ["iphone-16-pro"],
    mediaType: "photo",
    scenario: "night",
    lighting: ["night", "indoor-low-light"],
    outputGoals: ["maximum-quality", "edit-later", "private-sharing"],
    summary:
      "Stay at 1x, keep flash off, and let Night mode complete its capture. Brace the phone or use a tripod for multi-second exposures.",
    settings: {
      mode: "Photo (Night mode auto)",
      lens: "1x Main",
      format: "HEIF (ProRAW only if you will edit)",
      resolution: "24MP preferred; avoid 48MP unless locked down",
      hdr: "Automatic",
      nightMode: "Auto; increase seconds only when braced",
      flash: "Off",
      exposure: "Do not brighten aggressively—adds noise",
      focus: "Tap a mid-tone subject",
      photographicStyle: "Standard",
    },
    instructions: [
      "Open Photo mode and set zoom to 1x.",
      "When the moon icon appears, tap it to review Night mode seconds.",
      "Hold still against a wall or mount a tripod before tapping the shutter.",
      "Keep flash off—Night mode is for ambient light.",
      "Wait for the capture progress ring to finish before moving.",
    ],
    rationale: [
      {
        claim: "Night mode is designed for low light without flash.",
        sourceIds: ["apple-night-mode-support", "apple-camera-user-guide"],
      },
      {
        claim: "Controlled tests favored 1x and steady support over flash.",
        sourceIds: ["test-16pro-night-2026"],
      },
    ],
    alternatives: [
      {
        label: "Faster capture",
        reason: "Moving subjects or street scenes.",
        settingsSummary: "Keep Night seconds low · Live Photos off · 12MP",
        tradeoff: "More noise and less shadow detail.",
      },
      {
        label: "Edit later",
        reason: "Recover highlights and color in post.",
        settingsSummary: "Enable ProRAW · 1x · tripod",
        tradeoff: "Much larger files and slower workflow.",
      },
    ],
    mistakes: [
      "Using flash as a default night fix.",
      "Shooting 48MP handheld during long Night captures.",
      "Moving before the Night mode timer ends.",
    ],
    warnings: [
      "Night mode can take several seconds—warn subjects to stay still.",
      "ProRAW night files grow quickly; confirm free storage first.",
    ],
    requiredFeatures: ["nightMode"],
    accessoryTags: ["tripod", "MagSafe grip"],
    appTags: ["edit-photo", "manual-photo"],
    confidence: "high",
    evidence: [
      "Apple Night mode support",
      "Controlled night test · iPhone 16 Pro · iOS 18.5 · July 2026",
    ],
  }),
  rec({
    id: "15pro-portraits-daylight",
    modelIds: ["iphone-15-pro", "iphone-15-pro-max"],
    familyIds: ["iphone-15-pro"],
    mediaType: "photo",
    scenario: "portraits",
    lighting: ["daylight", "overcast", "indoor-daylight"],
    outputGoals: ["instagram", "private-sharing", "print"],
    summary:
      "Use Portrait mode around 2x with natural window or open-shade light. Keep flash off and refine depth after capture if needed.",
    settings: {
      mode: "Portrait",
      lens: "2x (or 1x for environmental portraits)",
      format: "HEIF",
      resolution: "Default Portrait output",
      hdr: "Automatic",
      flash: "Off",
      exposure: "Expose for the face",
      focus: "Tap the nearest eye",
      photographicStyle: "Standard or Rich Contrast lightly",
    },
    instructions: [
      "Switch to Portrait mode and stand a few feet from your subject.",
      "Choose 2x for classic head-and-shoulders framing.",
      "Place the subject with soft light on the face; avoid harsh noon sun.",
      "Wait for the depth effect preview, then shoot.",
      "Adjust f-stop and lighting effect later in Photos if needed.",
    ],
    rationale: [
      {
        claim: "Portrait mode is a native Camera mode with adjustable depth.",
        sourceIds: ["apple-camera-user-guide"],
      },
      {
        claim: "Controlled tests found 2x more flattering for faces on 15 Pro.",
        sourceIds: ["test-15pro-portrait-2026"],
      },
    ],
    alternatives: [
      {
        label: "Environmental portrait",
        reason: "Show more of the location.",
        settingsSummary: "Portrait 1x · softer depth · overcast light",
        tradeoff: "Backgrounds can look busier.",
      },
    ],
    mistakes: [
      "Standing too close—edges around hair and glasses can fail.",
      "Heavy backlight without exposing for the face.",
      "Relying on Studio Light effects that look artificial on social feeds.",
    ],
    requiredFeatures: [],
    accessoryTags: ["portable light", "MagSafe grip"],
    appTags: ["edit-photo"],
    confidence: "high",
    evidence: [
      "Apple Camera User Guide",
      "Controlled portrait test · iPhone 15 Pro · July 2026",
    ],
  }),
  rec({
    id: "16-family-selfies",
    modelIds: ["iphone-16", "iphone-16-plus", "iphone-16-pro", "iphone-16-pro-max"],
    familyIds: ["iphone-16", "iphone-16-pro"],
    mediaType: "photo",
    scenario: "selfies",
    lighting: ["indoor-daylight", "daylight", "overcast"],
    outputGoals: ["instagram", "private-sharing"],
    summary:
      "Use the front camera in Photo or Portrait, face a window, and keep the camera slightly above eye level. Avoid beauty filters in third-party apps if you want natural skin.",
    settings: {
      mode: "Photo or Portrait (front)",
      lens: "Front camera",
      format: "HEIF",
      flash: "Off (or Screen Light only if needed)",
      exposure: "Tap your face; lift slightly if underexposed",
      focus: "Tap eyes",
      photographicStyle: "Standard",
    },
    instructions: [
      "Flip to the front camera.",
      "Face a window or stand in open shade.",
      "Hold the phone slightly above eye level and extend your arm.",
      "Tap your face to set focus and exposure.",
      "Use Portrait front mode only when there is enough light for a clean depth map.",
    ],
    rationale: [
      {
        claim: "Front camera Night/Portrait behavior depends on available light.",
        sourceIds: ["apple-camera-user-guide"],
      },
    ],
    alternatives: [
      {
        label: "Low light selfie",
        reason: "Dim rooms.",
        settingsSummary: "Front Photo · Screen Light if needed · avoid heavy digital zoom",
        tradeoff: "Softer detail and flatter skin texture.",
      },
    ],
    mistakes: [
      "Shooting under warm overhead bulbs that tint skin orange.",
      "Holding the phone too low (unflattering angle).",
    ],
    accessoryTags: ["portable light"],
    appTags: ["edit-photo"],
    confidence: "medium",
    evidence: ["Apple Camera User Guide", "Limited front-camera lighting checks"],
  }),
  rec({
    id: "pro-food-indoor",
    modelIds: [
      "iphone-16-pro",
      "iphone-16-pro-max",
      "iphone-15-pro",
      "iphone-15-pro-max",
      "iphone-14-pro",
      "iphone-14-pro-max",
    ],
    familyIds: ["iphone-16-pro", "iphone-15-pro", "iphone-14-pro"],
    mediaType: "photo",
    scenario: "food",
    lighting: ["indoor-daylight", "overcast", "indoor-low-light"],
    outputGoals: ["instagram", "private-sharing"],
    summary:
      "Shoot from a 45° angle at 1x or Macro when close, with window light as the key light. Keep flash off and slightly desaturate later if colors look too punchy.",
    settings: {
      mode: "Photo",
      lens: "1x (Macro auto when very close on Pro)",
      format: "HEIF",
      flash: "Off",
      exposure: "Slightly darker than default to protect highlights on plates",
      focus: "Tap the hero ingredient",
      photographicStyle: "Standard",
      nightMode: "Allow auto indoors if needed",
    },
    instructions: [
      "Place the dish near a window; turn off mixed warm overheads if possible.",
      "Shoot at 1x from a 45° angle or directly above for flat lays.",
      "On Pro models, let Macro engage only when intentional—tap to lock out if unwanted.",
      "Lower exposure a touch so white plates retain texture.",
      "Capture one wider plate shot and one detail crop.",
    ],
    rationale: [
      {
        claim: "Macro is available on Pro models via the Ultra Wide camera.",
        sourceIds: ["apple-iphone-15-pro-specs", "apple-iphone-16-pro-specs"],
      },
    ],
    alternatives: [
      {
        label: "Dim restaurant",
        reason: "Low ambient light.",
        settingsSummary: "1x · Night auto · portable light off-camera if allowed",
        tradeoff: "Motion blur if hands shake.",
      },
    ],
    mistakes: [
      "On-camera flash bouncing off glossy sauces.",
      "Shooting under deep orange restaurant bulbs without white-balance fixes later.",
    ],
    requiredFeatures: [],
    accessoryTags: ["portable light"],
    appTags: ["edit-photo"],
    confidence: "medium",
    evidence: ["Apple Pro specs for Macro", "Editorial food lighting checks"],
  }),
  rec({
    id: "travel-landscape-photo",
    modelIds: [
      "iphone-16-pro",
      "iphone-16-pro-max",
      "iphone-15-pro",
      "iphone-15-pro-max",
      "iphone-16",
      "iphone-16-plus",
      "iphone-15",
      "iphone-15-plus",
    ],
    familyIds: ["iphone-16-pro", "iphone-15-pro", "iphone-16", "iphone-15"],
    mediaType: "photo",
    scenario: "travel",
    lighting: ["daylight", "overcast", "backlight"],
    outputGoals: ["edit-later", "maximum-quality", "print"],
    summary:
      "Prefer 1x or 0.5x HEIF at 24MP/48MP in good light. For backlit landmarks, tap the subject and raise exposure carefully, or bracket with a second darker frame.",
    settings: {
      mode: "Photo",
      lens: "1x primary; 0.5x for expansive scenes",
      format: "HEIF or ProRAW (Pro models, edit later)",
      resolution: "24MP or 48MP in strong light",
      hdr: "Smart HDR on",
      flash: "Off",
      exposure: "Protect bright skies; lift shadows later if needed",
      focus: "Tap a mid-ground subject",
      photographicStyle: "Standard",
    },
    instructions: [
      "Clean the lenses—travel dust softens fine detail.",
      "Start at 1x; switch to 0.5x only when the scene needs width.",
      "On Pro models, enable ProRAW only for keepers you will edit.",
      "Hold elbows in and breathe out as you tap the shutter.",
      "Capture a second frame if the sky is blown out.",
    ],
    rationale: [
      {
        claim: "48MP main cameras on recent iPhones support higher stills resolution.",
        sourceIds: ["apple-iphone-16-pro-specs", "apple-iphone-15-pro-specs", "apple-iphone-15-specs"],
      },
      {
        claim: "ProRAW is intended for editing flexibility on Pro models.",
        sourceIds: ["apple-proraw-support"],
      },
    ],
    alternatives: [
      {
        label: "Save storage on the road",
        reason: "Long trips fill free space.",
        settingsSummary: "HEIF · 12MP · Live Photos off · ProRAW off",
        tradeoff: "Less crop and edit latitude.",
      },
    ],
    mistakes: [
      "Shooting everything in ProRAW and running out of storage mid-trip.",
      "Using telephoto through dirty glass on buses or planes.",
    ],
    warnings: ["ProRAW and 48MP increase storage use significantly."],
    accessoryTags: ["tripod", "power bank", "external storage"],
    appTags: ["edit-photo"],
    confidence: "high",
    evidence: ["Apple specs", "Apple ProRAW support article"],
  }),
  rec({
    id: "kids-pets-photo",
    modelIds: [
      "iphone-16",
      "iphone-16-plus",
      "iphone-16-pro",
      "iphone-16-pro-max",
      "iphone-15",
      "iphone-15-plus",
      "iphone-15-pro",
      "iphone-15-pro-max",
      "iphone-14",
      "iphone-14-plus",
      "iphone-14-pro",
      "iphone-14-pro-max",
      "iphone-13",
      "iphone-13-mini",
      "iphone-13-pro",
      "iphone-13-pro-max",
    ],
    mediaType: "photo",
    scenario: "kids-pets",
    lighting: ["daylight", "overcast", "indoor-daylight"],
    outputGoals: ["private-sharing", "save-storage", "instagram"],
    summary:
      "Prioritize speed: Photo mode at 1x, Live Photos optional, burst for peak action. Avoid Night mode waits and heavy formats while subjects move.",
    settings: {
      mode: "Photo",
      lens: "1x",
      format: "HEIF",
      resolution: "12MP for speed",
      nightMode: "Avoid long captures",
      flash: "Off",
      exposure: "Tap subject",
      focus: "Track the face/eyes; retap often",
      photographicStyle: "Standard",
    },
    instructions: [
      "Use Photo mode at 1x with plenty of light.",
      "Hold the shutter for burst when action peaks.",
      "Keep Live Photos on only if you want the micro-video context.",
      "Turn off ProRAW and 48MP for moving subjects.",
      "Get closer physically instead of zooming.",
    ],
    rationale: [
      {
        claim: "Native Camera supports burst photography for action.",
        sourceIds: ["apple-camera-user-guide"],
      },
    ],
    alternatives: [
      {
        label: "Video fallback",
        reason: "Unpredictable motion.",
        settingsSummary: "4K30 or 1080p60 · Action mode if available",
        tradeoff: "Still frame grabs are softer than dedicated stills.",
      },
    ],
    mistakes: [
      "Waiting on Night mode while a child runs.",
      "Chasing with digital zoom and ending up with mushy crops.",
    ],
    accessoryTags: ["MagSafe grip"],
    appTags: ["edit-photo"],
    confidence: "medium",
    evidence: ["Apple Camera User Guide", "Editorial action shooting notes"],
  }),
  rec({
    id: "sports-action-photo-video",
    modelIds: [
      "iphone-16-pro",
      "iphone-16-pro-max",
      "iphone-16",
      "iphone-16-plus",
      "iphone-15-pro",
      "iphone-15-pro-max",
      "iphone-15",
      "iphone-15-plus",
      "iphone-14-pro",
      "iphone-14-pro-max",
      "iphone-14",
      "iphone-14-plus",
    ],
    familyIds: ["iphone-16-pro", "iphone-16", "iphone-15-pro", "iphone-15", "iphone-14-pro", "iphone-14"],
    mediaType: "video",
    scenario: "sports",
    lighting: ["daylight", "overcast"],
    outputGoals: ["edit-later", "youtube", "private-sharing"],
    summary:
      "Record 4K60 when light allows, or 1080p60 for longer events. Enable Action mode only when walking/running with the camera; it crops the frame.",
    settings: {
      mode: "Video",
      lens: "1x",
      format: "HEVC High Efficiency",
      resolution: "4K",
      frameRate: "60 fps (30 fps if storage-limited)",
      hdr: "HDR Video on unless delivering SDR",
      stabilization: "Standard; Action mode when needed",
      exposure: "Lock AE/AF if lighting is consistent",
    },
    instructions: [
      "In Settings → Camera → Record Video, choose 4K at 60 fps if storage allows.",
      "Start at 1x; avoid constant zooming while recording.",
      "Turn on Action mode only for handheld run-and-gun clips.",
      "Lock focus/exposure on the field if auto exposure pumps.",
      "Monitor storage—4K60 fills space quickly.",
    ],
    rationale: [
      {
        claim: "Supported video resolutions and frame rates vary by model and are listed in Apple specs.",
        sourceIds: ["apple-iphone-16-pro-specs", "apple-iphone-15-pro-specs", "apple-camera-user-guide"],
      },
      {
        claim: "Action mode is available on iPhone 14 and later.",
        sourceIds: ["apple-iphone-14-specs", "apple-camera-user-guide"],
      },
    ],
    alternatives: [
      {
        label: "Storage saver",
        reason: "All-day events.",
        settingsSummary: "1080p60 · HEVC · HDR off if not needed",
        tradeoff: "Less detail for large-screen edits.",
      },
    ],
    mistakes: [
      "Leaving Action mode on for tripod shots (unnecessary crop).",
      "Recording ProRes for casual sports when you only need social clips.",
    ],
    warnings: ["Action mode crops the field of view."],
    requiredFeatures: ["actionMode"],
    accessoryTags: ["gimbal", "power bank", "external storage"],
    appTags: ["manual-video", "pro-video"],
    confidence: "high",
    evidence: ["Apple specs", "Apple Camera User Guide"],
  }),
  rec({
    id: "tiktok-vertical-video",
    modelIds: [
      "iphone-16",
      "iphone-16-plus",
      "iphone-16-pro",
      "iphone-16-pro-max",
      "iphone-15",
      "iphone-15-plus",
      "iphone-15-pro",
      "iphone-15-pro-max",
      "iphone-14",
      "iphone-14-plus",
      "iphone-14-pro",
      "iphone-14-pro-max",
    ],
    mediaType: "video",
    scenario: "tiktok",
    lighting: ["indoor-daylight", "daylight", "indoor-low-light"],
    outputGoals: ["tiktok", "instagram", "save-storage"],
    summary:
      "Shoot vertical 1080p30 or 4K30 in good light, lock exposure, and prioritize clean audio. Social platforms recompress aggressively—lighting matters more than max resolution.",
    settings: {
      mode: "Video",
      lens: "1x front or rear",
      format: "HEVC",
      resolution: "1080p (or 4K if you crop later)",
      frameRate: "30 fps",
      hdr: "Off for more predictable social colors",
      stabilization: "Standard",
      exposure: "Lock on face",
    },
    instructions: [
      "Hold the phone vertically before recording.",
      "Use 1080p30 for most TikTok clips; step up to 4K only if you will reframe.",
      "Face a window or soft lamp; avoid strong overhead mixed light.",
      "Lock AE/AF on your face.",
      "Use a clip-on mic for talking videos when possible.",
    ],
    rationale: [
      {
        claim: "Controlled social compression tests found 1080p30 sufficient for TikTok delivery.",
        sourceIds: ["test-video-social-2026"],
      },
      {
        claim: "HEVC is the efficient video format path on iPhone.",
        sourceIds: ["apple-heif-support"],
      },
    ],
    alternatives: [
      {
        label: "Higher quality master",
        reason: "Repurpose for YouTube Shorts and Reels.",
        settingsSummary: "4K30 · HEVC · HDR off · mic",
        tradeoff: "Larger files and longer exports.",
      },
    ],
    mistakes: [
      "Recording horizontally and cropping later into a soft vertical frame.",
      "Relying on built-in mic in windy outdoor locations.",
    ],
    accessoryTags: ["microphone", "portable light", "MagSafe grip"],
    appTags: ["social-edit"],
    confidence: "medium",
    evidence: [
      "Social video compression comparison · July 2026",
      "Apple HEIF/HEVC documentation",
    ],
  }),
  rec({
    id: "youtube-video-pro",
    modelIds: [
      "iphone-16-pro",
      "iphone-16-pro-max",
      "iphone-15-pro",
      "iphone-15-pro-max",
      "iphone-14-pro",
      "iphone-14-pro-max",
    ],
    familyIds: ["iphone-16-pro", "iphone-15-pro", "iphone-14-pro"],
    mediaType: "video",
    scenario: "youtube",
    lighting: ["indoor-daylight", "daylight", "overcast"],
    outputGoals: ["youtube", "edit-later", "maximum-quality"],
    summary:
      "Record 4K30 HEVC for most talking-head and travel YouTube. Use ProRes or Log only when you have storage, a monitoring plan, and a color workflow.",
    settings: {
      mode: "Video",
      lens: "1x",
      format: "HEVC (ProRes only for graded projects)",
      resolution: "4K",
      frameRate: "30 fps (24 fps for cinematic intentional look)",
      hdr: "Match your delivery; SDR is simpler for many channels",
      stabilization: "Standard; gimbal for walks",
      exposure: "Lock AE/AF; expose for skin highlights",
    },
    instructions: [
      "Set Record Video to 4K at 30 fps in Settings → Camera.",
      "Enable Grid and keep the camera at eye level for talking heads.",
      "Lock exposure on your face once lighting is set.",
      "Skip ProRes unless you will color grade and have external storage.",
      "Capture 10 seconds of room tone for edit flexibility.",
    ],
    rationale: [
      {
        claim: "Pro models support ProRes; non-Pro models do not.",
        sourceIds: ["apple-iphone-16-pro-specs", "apple-iphone-15-pro-specs"],
      },
      {
        claim: "4K30 is a practical YouTube master based on controlled tests.",
        sourceIds: ["test-video-social-2026"],
      },
    ],
    alternatives: [
      {
        label: "Cinematic grade workflow",
        reason: "Color-managed projects.",
        settingsSummary: "ProRes or Apple Log where supported · external SSD · manual app",
        tradeoff: "Heavy storage and more complex editing.",
      },
    ],
    mistakes: [
      "Turning on Apple Log without a conversion workflow.",
      "Mixing HDR and SDR clips in one timeline unintentionally.",
    ],
    warnings: [
      "ProRes requires substantial free storage and may need external media.",
      "Apple Log is not available on all Pro generations—verify before recommending.",
    ],
    requiredFeatures: ["proRes"],
    accessoryTags: ["microphone", "gimbal", "portable light", "external storage", "power bank"],
    appTags: ["manual-video", "pro-video"],
    confidence: "high",
    evidence: [
      "Apple Pro specs",
      "Social/YouTube compression comparison · July 2026",
    ],
  }),
  rec({
    id: "concerts-mixed-light",
    modelIds: [
      "iphone-16-pro",
      "iphone-16-pro-max",
      "iphone-15-pro",
      "iphone-15-pro-max",
      "iphone-14-pro",
      "iphone-14-pro-max",
      "iphone-16",
      "iphone-15",
      "iphone-14",
    ],
    mediaType: "photo",
    scenario: "concerts",
    lighting: ["mixed-stage", "night", "indoor-low-light"],
    outputGoals: ["private-sharing", "instagram", "save-storage"],
    summary:
      "Expect noisy, colorful light. Prefer 1x or optical telephoto, disable flash, and accept shorter Night captures. Video at 4K30 or 1080p60 often beats stills for moving performers.",
    settings: {
      mode: "Photo or Video",
      lens: "1x or optical telephoto (3x/5x when available)",
      format: "HEIF / HEVC",
      resolution: "12MP stills; 1080p60 or 4K30 video",
      nightMode: "Keep seconds short",
      flash: "Off",
      exposure: "Expose for the performer highlights",
      focus: "Tap the subject repeatedly as lights change",
      photographicStyle: "Standard",
    },
    instructions: [
      "Turn flash off—venues often prohibit it and it ruins atmosphere.",
      "Use 1x; switch to optical telephoto only if you are far back.",
      "Lock exposure when stage lights stabilize briefly.",
      "For video, stabilize against your body and avoid digital zoom.",
      "Shoot short clips instead of one long rolling file.",
    ],
    rationale: [
      {
        claim: "Optical telephoto availability depends on model (3x vs 5x).",
        sourceIds: ["apple-iphone-16-pro-specs", "apple-iphone-15-pro-specs"],
      },
    ],
    alternatives: [
      {
        label: "Video-first",
        reason: "Performers move constantly.",
        settingsSummary: "1080p60 · AE lock · no Action mode if already steady",
        tradeoff: "Still frame grabs are softer.",
      },
    ],
    mistakes: [
      "Max digital zoom from the back of the venue.",
      "Using flash and getting you or nearby fans blocked by staff.",
    ],
    accessoryTags: ["MagSafe grip"],
    appTags: ["edit-photo", "social-edit"],
    confidence: "experimental",
    evidence: [
      "Capability data for lenses",
      "Limited venue testing — treat as experimental guidance",
    ],
    status: "reviewed",
  }),
  rec({
    id: "weddings-guest-photo",
    modelIds: [
      "iphone-16-pro",
      "iphone-16-pro-max",
      "iphone-15-pro",
      "iphone-15-pro-max",
      "iphone-14-pro",
      "iphone-14-pro-max",
      "iphone-16",
      "iphone-15",
      "iphone-14",
      "iphone-13-pro",
    ],
    mediaType: "photo",
    scenario: "weddings",
    lighting: ["mixed-stage", "indoor-daylight", "daylight", "indoor-low-light"],
    outputGoals: ["maximum-quality", "private-sharing", "print"],
    summary:
      "As a guest, prioritize quiet, accurate moments: Photo mode, 1x–2x, HEIF, flash off during ceremonies. Use Portrait sparingly and keep shutter sounds / brightness considerate.",
    settings: {
      mode: "Photo (Portrait for posed groups when light allows)",
      lens: "1x or 2x",
      format: "HEIF",
      resolution: "24MP when available",
      flash: "Off during ceremony",
      nightMode: "Auto for dim receptions",
      exposure: "Expose for faces, especially in mixed lighting",
      focus: "Tap eyes",
      photographicStyle: "Standard",
    },
    instructions: [
      "Silence the phone and lower screen brightness before the ceremony.",
      "Use 1x or 2x from your seat—do not block aisles or the pro photographer.",
      "Keep flash off for vows and processions.",
      "At receptions, allow Night mode and brace against a chair if needed.",
      "Capture candids between formal shots rather than competing with hired coverage.",
    ],
    rationale: [
      {
        claim: "Native Camera modes cover Photo and Portrait without third-party apps.",
        sourceIds: ["apple-camera-user-guide"],
      },
    ],
    alternatives: [
      {
        label: "Reception video toast",
        reason: "Speeches and dances.",
        settingsSummary: "4K30 or 1080p30 · mic closer if appropriate · AE lock",
        tradeoff: "Audio may still be roomy without an external mic.",
      },
    ],
    mistakes: [
      "Using flash during the ceremony.",
      "Standing in the professional photographer’s line of sight.",
    ],
    accessoryTags: ["MagSafe grip", "portable light"],
    appTags: ["edit-photo"],
    confidence: "medium",
    evidence: ["Apple Camera User Guide", "Editorial guest-photography checklist"],
  }),
  rec({
    id: "instagram-photo-default",
    modelIds: [
      "iphone-16",
      "iphone-16-plus",
      "iphone-16-pro",
      "iphone-16-pro-max",
      "iphone-15",
      "iphone-15-plus",
      "iphone-15-pro",
      "iphone-15-pro-max",
    ],
    familyIds: ["iphone-16", "iphone-16-pro", "iphone-15", "iphone-15-pro"],
    mediaType: "photo",
    scenario: "instagram",
    lighting: ["daylight", "overcast", "indoor-daylight"],
    outputGoals: ["instagram", "private-sharing"],
    summary:
      "Shoot HEIF at 1x with a clean Photographic Style, then crop for feed ratios in Photos. Avoid over-sharpened third-party filters before upload.",
    settings: {
      mode: "Photo",
      lens: "1x (2x for tighter portraits)",
      format: "HEIF",
      resolution: "24MP when available",
      hdr: "On",
      flash: "Off",
      photographicStyle: "Vibrant or Standard",
      exposure: "Slightly conservative to protect highlights",
    },
    instructions: [
      "Capture at 1x with intentional framing—leave a little room to crop.",
      "Use Photographic Style sparingly; Instagram will recompress again.",
      "Edit crops to 4:5 for feed or 9:16 for Stories/Reels covers.",
      "Export or share from Photos; avoid repeated re-saves as JPEG.",
    ],
    rationale: [
      {
        claim: "HEIF remains the efficient capture format before social upload.",
        sourceIds: ["apple-heif-support"],
      },
    ],
    alternatives: [
      {
        label: "Maximum quality archive",
        reason: "Keep a better master than the Instagram upload.",
        settingsSummary: "HEIF 24/48MP master · separate cropped share copy",
        tradeoff: "Two files to manage.",
      },
    ],
    mistakes: [
      "Uploading screenshots of photos.",
      "Applying stacked filters in multiple apps before posting.",
    ],
    accessoryTags: ["portable light", "MagSafe grip"],
    appTags: ["edit-photo", "social-edit"],
    confidence: "medium",
    evidence: ["Apple HEIF documentation", "Editorial social upload checks"],
  }),
  rec({
    id: "13pro-everyday-fallback",
    modelIds: ["iphone-13-pro", "iphone-13-pro-max", "iphone-13", "iphone-13-mini"],
    familyIds: ["iphone-13-pro", "iphone-13"],
    mediaType: "photo",
    scenario: "everyday",
    lighting: ["daylight", "overcast", "indoor-daylight"],
    outputGoals: ["private-sharing", "instagram", "save-storage"],
    summary:
      "On iPhone 13 families, stick to Photo mode at 1x with HEIF. Pro models can use ProRAW selectively; non-Pro models should stay on HEIF and avoid unsupported Pro features.",
    settings: {
      mode: "Photo",
      lens: "1x",
      format: "HEIF (ProRAW on Pro only when editing)",
      resolution: "12MP",
      hdr: "Smart HDR on",
      flash: "Off",
      photographicStyle: "Standard",
      nightMode: "Auto in low light",
    },
    instructions: [
      "Open Photo mode at 1x.",
      "Confirm High Efficiency in Settings → Camera → Formats.",
      "On Pro models, enable ProRAW only for planned edits.",
      "Do not expect Action mode—it is not available on iPhone 13.",
    ],
    rationale: [
      {
        claim: "iPhone 13 Pro supports ProRAW; iPhone 13/mini do not.",
        sourceIds: ["apple-iphone-13-pro-specs", "apple-iphone-13-specs", "apple-proraw-support"],
      },
    ],
    alternatives: [
      {
        label: "Low light",
        reason: "Evening walks and indoor dinners.",
        settingsSummary: "1x · Night mode auto · brace phone",
        tradeoff: "Subject motion can blur during longer captures.",
      },
    ],
    mistakes: [
      "Following newer Pro tutorials that assume 48MP or Action mode.",
    ],
    warnings: ["Action mode is not available on iPhone 13 family."],
    accessoryTags: ["MagSafe grip"],
    appTags: ["edit-photo"],
    confidence: "high",
    evidence: ["Apple iPhone 13/13 Pro specifications", "Apple ProRAW article"],
  }),
  // Draft example intentionally not indexed heavily
  rec({
    id: "draft-concert-log-video",
    modelIds: ["iphone-16-pro", "iphone-16-pro-max"],
    mediaType: "video",
    scenario: "concerts",
    lighting: ["mixed-stage"],
    outputGoals: ["edit-later"],
    summary:
      "Experimental: Apple Log for concert video is plausible for advanced editors but not fully validated across venues.",
    settings: {
      mode: "Video / Log-capable app",
      lens: "1x",
      format: "Apple Log where supported",
      resolution: "4K",
      frameRate: "30 fps",
    },
    instructions: [
      "Only use Log if you can convert it in post.",
      "Confirm the specific iOS build exposes Log for your model.",
    ],
    rationale: [
      {
        claim: "Apple Log is listed for iPhone 16 Pro capabilities.",
        sourceIds: ["apple-iphone-16-pro-specs"],
      },
    ],
    alternatives: [],
    mistakes: ["Publishing unconverted Log footage that looks flat and gray."],
    requiredFeatures: ["appleLog"],
    accessoryTags: ["external storage"],
    appTags: ["manual-video"],
    confidence: "experimental",
    evidence: ["Apple specs only — venue testing incomplete"],
    status: "draft",
  }),
];

export const recommendationsById = Object.fromEntries(
  recommendations.map((r) => [r.id, r]),
);
