import type { Source } from "@/lib/schemas";

export const sources: Source[] = [
  {
    id: "apple-camera-user-guide",
    tier: 1,
    publisher: "Apple",
    title: "iPhone User Guide — Camera",
    url: "https://support.apple.com/guide/iphone/camera-iph3e283366/ios",
    accessedAt: "2026-07-01",
    supportedClaims: [
      "native-camera-modes",
      "night-mode",
      "photographic-styles",
      "live-photos",
      "video-controls",
      "preserve-settings",
    ],
  },
  {
    id: "apple-iphone-16-pro-specs",
    tier: 1,
    publisher: "Apple",
    title: "iPhone 16 Pro and iPhone 16 Pro Max — Technical Specifications",
    url: "https://www.apple.com/iphone-16-pro/specs/",
    accessedAt: "2026-07-01",
    testedModels: ["iphone-16-pro", "iphone-16-pro-max"],
    supportedClaims: [
      "48mp-fusion",
      "5x-telephoto",
      "proraw",
      "prores",
      "apple-log",
      "4k120",
      "lenses-0.5-1-2-5",
    ],
  },
  {
    id: "apple-iphone-16-specs",
    tier: 1,
    publisher: "Apple",
    title: "iPhone 16 and iPhone 16 Plus — Technical Specifications",
    url: "https://www.apple.com/iphone-16/specs/",
    accessedAt: "2026-07-01",
    testedModels: ["iphone-16", "iphone-16-plus"],
    supportedClaims: ["48mp-main", "no-proraw", "cinematic-mode", "action-mode"],
  },
  {
    id: "apple-iphone-15-pro-specs",
    tier: 1,
    publisher: "Apple",
    title: "iPhone 15 Pro and iPhone 15 Pro Max — Technical Specifications",
    url: "https://www.apple.com/iphone-15-pro/specs/",
    accessedAt: "2026-07-01",
    testedModels: ["iphone-15-pro", "iphone-15-pro-max"],
    supportedClaims: ["48mp-main", "proraw", "prores", "3x-or-5x-telephoto"],
  },
  {
    id: "apple-iphone-15-specs",
    tier: 1,
    publisher: "Apple",
    title: "iPhone 15 and iPhone 15 Plus — Technical Specifications",
    url: "https://www.apple.com/iphone-15/specs/",
    accessedAt: "2026-07-01",
    testedModels: ["iphone-15", "iphone-15-plus"],
    supportedClaims: ["48mp-main", "no-proraw", "2x-crop"],
  },
  {
    id: "apple-iphone-14-pro-specs",
    tier: 1,
    publisher: "Apple",
    title: "iPhone 14 Pro and iPhone 14 Pro Max — Technical Specifications",
    url: "https://support.apple.com/kb/SP875",
    accessedAt: "2026-07-01",
    testedModels: ["iphone-14-pro", "iphone-14-pro-max"],
    supportedClaims: ["48mp-main", "proraw", "prores", "3x-telephoto"],
  },
  {
    id: "apple-iphone-14-specs",
    tier: 1,
    publisher: "Apple",
    title: "iPhone 14 and iPhone 14 Plus — Technical Specifications",
    url: "https://support.apple.com/kb/SP874",
    accessedAt: "2026-07-01",
    testedModels: ["iphone-14", "iphone-14-plus"],
    supportedClaims: ["12mp-dual", "cinematic-mode", "action-mode"],
  },
  {
    id: "apple-iphone-13-pro-specs",
    tier: 1,
    publisher: "Apple",
    title: "iPhone 13 Pro and iPhone 13 Pro Max — Technical Specifications",
    url: "https://support.apple.com/kb/SP852",
    accessedAt: "2026-07-01",
    testedModels: ["iphone-13-pro", "iphone-13-pro-max"],
    supportedClaims: ["proraw", "prores", "macro", "3x-telephoto"],
  },
  {
    id: "apple-iphone-13-specs",
    tier: 1,
    publisher: "Apple",
    title: "iPhone 13 and iPhone 13 mini — Technical Specifications",
    url: "https://support.apple.com/kb/SP851",
    accessedAt: "2026-07-01",
    testedModels: ["iphone-13", "iphone-13-mini"],
    supportedClaims: ["12mp-dual", "cinematic-mode", "night-mode"],
  },
  {
    id: "apple-heif-support",
    tier: 1,
    publisher: "Apple",
    title: "Use HEIF or HEVC media on Apple devices",
    url: "https://support.apple.com/HT207022",
    accessedAt: "2026-07-01",
    supportedClaims: ["heif-default", "jpeg-compatibility", "hevc-video"],
  },
  {
    id: "apple-proraw-support",
    tier: 1,
    publisher: "Apple",
    title: "About Apple ProRAW",
    url: "https://support.apple.com/HT211965",
    accessedAt: "2026-07-01",
    supportedClaims: ["proraw-pro-only", "proraw-edit-flexibility", "proraw-file-size"],
  },
  {
    id: "apple-night-mode-support",
    tier: 1,
    publisher: "Apple",
    title: "Take great photos in low light or at night with Night mode",
    url: "https://support.apple.com/HT211029",
    accessedAt: "2026-07-01",
    supportedClaims: ["night-mode-auto", "night-mode-hold-steady", "night-mode-flash-off"],
  },
  {
    id: "test-16pro-night-2026",
    tier: 2,
    publisher: "Best iPhone Camera Settings",
    title: "Controlled night photography test — iPhone 16 Pro",
    accessedAt: "2026-07-10",
    testedModels: ["iphone-16-pro"],
    testedIOS: ["18.5"],
    supportedClaims: [
      "1x-night-detail",
      "tripod-helps-night",
      "flash-washes-scenes",
      "48mp-night-slower",
    ],
  },
  {
    id: "test-15pro-portrait-2026",
    tier: 2,
    publisher: "Best iPhone Camera Settings",
    title: "Controlled portrait lighting test — iPhone 15 Pro",
    accessedAt: "2026-07-08",
    testedModels: ["iphone-15-pro"],
    testedIOS: ["18.5"],
    supportedClaims: [
      "2x-portrait-flattering",
      "portrait-mode-edge-cases",
      "natural-light-better-skin",
    ],
  },
  {
    id: "test-video-social-2026",
    tier: 2,
    publisher: "Best iPhone Camera Settings",
    title: "Social video compression comparison",
    accessedAt: "2026-07-12",
    testedModels: ["iphone-16", "iphone-15-pro"],
    testedIOS: ["18.5"],
    supportedClaims: [
      "4k30-good-youtube",
      "1080p30-enough-tiktok",
      "hevc-smaller-files",
    ],
  },
  {
    id: "dxomark-iphone-camera",
    tier: 3,
    publisher: "DXOMARK",
    title: "Independent smartphone camera testing methodology",
    url: "https://www.dxomark.com/",
    accessedAt: "2026-06-20",
    supportedClaims: ["independent-lab-context"],
  },
];

export const sourcesById = Object.fromEntries(sources.map((s) => [s.id, s]));
